<?php
/**
 * TDProject_Core
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
?>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<title><?php echo $this->getPageTitle() ?></title>
<?php foreach ($this->_getChilds() as $child) { ?>
	<?php $this->_getChildHtml($child->getBlockName()); ?>
<?php } ?>
</head>