<label for="<?php echo $this->getBlockName() ?>" class="<?php echo $this->getCssClass() ?>">
	<span class="title"><?php echo $this->getBlockTitle() ?>:</span><?php if ($this->isMandatory()) { ?>&nbsp;<span class="required">*</span><?php } ?>
	<input 
		type="checkbox"
		value="1" 
		name="<?php echo $this->getBlockName() ?>" 
		id="<?php echo $this->getBlockName() ?>" 
		<?php if ($this->isDisabled()) { ?> disabled="disabled"<?php } ?> 
		<?php if ($this->getValue()->booleanValue()) { ?>checked="checked" <?php } ?>/>
</label>