<label for="<?php echo $this->getBlockName() ?>" class="<?php echo $this->getCssClass() ?>">
	<span class="title"><?php echo $this->getBlockTitle() ?>:</span><?php if ($this->isMandatory()) { ?>&nbsp;<span class="required">*</span><?php } ?>
	<input   
		type="password"
		size="<?php echo $this->getSize() ?>"
		maxlength="<?php echo $this->getMaxLength() ?>"
		id="<?php echo $this->getBlockName() ?>"
		name="<?php echo $this->getBlockName() ?>"
		value="<?php echo $this->getValue(); ?>"
		<?php if ($this->isDisabled()) { ?> disabled="disabled"<?php } ?> />
</label>