<?php

/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
?>
<p>
	<span><?php echo $this->translate('widget.breadcrumb.overview', 'Widgets') ?>: </span><b><?php echo $this->getBlockTitle(); ?></b>
</p>

<form id="<?php echo $this->getCssId() ?>" name="<?php echo $this->getFormName() ?>" method="post" class="yform">
	<?php $this->_getChildHtml('toolbar') ?>
	
	<?php foreach ($this->_getChilds() as $child) { ?>
		<?php $this->_getChildHtml($child->getBlockName()) ?>
	<?php } ?>
</form>