<?php

/**
 * TDProject_Core
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

?>
<td width="<?php echo $this->getWidth() ?>%"><?php foreach ($this->_getChilds() as $child) { ?>
	<?php $this->_getChildHtml($child->getBlockName()) ?>
<?php }?></td>