<?php
/**
 * TDProject_Core
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
?>
<form class="yform">
	<fieldset class="ui-widget ui-widget-content ui-corner-all">
    	<legend>Test-Widget</legend>
    	<div class="type-text">
    		<label>
    			Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean 
    			commodo ligula eget dolor. Aenean massa. Cum sociis natoque 
    			penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    		</label>
		</div>
	</fieldset>
</form>