ALTER TABLE `role` 
	ADD `role_id_fk` INT NULL AFTER `role_id` ,
	ADD `user_id_fk` INT NULL AFTER `role_id_fk`;
	
ALTER TABLE `role` ADD INDEX `role_idx_01` ( `role_id_fk` );
ALTER TABLE `role` ADD INDEX `role_idx_02` ( `user_id_fk` );

ALTER TABLE `role` ADD FOREIGN KEY ( `role_id_fk` ) REFERENCES `role` ( `role_id` ) ON DELETE CASCADE;
ALTER TABLE `role` ADD FOREIGN KEY ( `user_id_fk` ) REFERENCES `user` ( `user_id` ) ON DELETE CASCADE;

INSERT INTO `role` (`role_id`, `role_id_fk`, `user_id_fk`, `name`) VALUES (3, NULL, NULL, 'Guest');
INSERT INTO `role` (`role_id`, `role_id_fk`, `user_id_fk`, `name`) VALUES (4, 3, NULL, 'Developer');
INSERT INTO `role` (`role_id`, `role_id_fk`, `user_id_fk`, `name`) VALUES (5, 2, NULL, 'Projectmanager');

UPDATE `role` SET `role_id_fk` = 4 WHERE `role_id` = 2;
UPDATE `role` SET `role_id_fk` = 2 WHERE `role_id` = 5;
UPDATE `role` SET `role_id_fk` = 5 WHERE `role_id` = 1;

INSERT INTO `role` (`role_id_fk`, `user_id_fk`, `name`) SELECT `role_id_fk`, `user_id`, `username` FROM `user`;

ALTER TABLE `user` DROP INDEX `user_idx_01`;
ALTER TABLE `user` DROP `role_id_fk`; 
ALTER TABLE `user` ADD `contracted_hours` INT NOT NULL DEFAULT '160' AFTER `rate`;

CREATE TABLE `assertion` (
	`assertion_id` int(10) NOT NULL, 
	`type` varchar(255) NOT NULL, 
	`include_file` varchar(255) NOT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ENGINE=ndbcluster;

ALTER TABLE `assertion` ADD CONSTRAINT assertion_pk PRIMARY KEY (`assertion_id`); 
ALTER TABLE `assertion` CHANGE assertion_id `assertion_id` int(10) AUTO_INCREMENT;
        
CREATE TABLE `rule` (
	`rule_id` int(10) NOT NULL, 
	`role_id_fk` int(10) NOT NULL, 
	`assertion_id_fk` int(10), 
	`resource` varchar(255) NOT NULL, 
	`privileges` varchar(255),
	`permission` varchar(255) NOT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ENGINE=ndbcluster;       

ALTER TABLE `rule` ADD CONSTRAINT rule_pk PRIMARY KEY (`rule_id`); 
ALTER TABLE `rule` CHANGE rule_id `rule_id` int(10) AUTO_INCREMENT;

CREATE INDEX rule_idx_01 ON `rule` (`role_id_fk`);
CREATE INDEX rule_idx_02 ON `rule` (`assertion_id_fk`);
ALTER TABLE `rule` ADD UNIQUE `rule_uidx_01` (`role_id_fk`, `resource`);

ALTER TABLE `rule` ADD CONSTRAINT rule_fk_01 FOREIGN KEY (`role_id_fk`) REFERENCES `role` (`role_id`);
ALTER TABLE `rule` ADD CONSTRAINT rule_fk_02 FOREIGN KEY (`assertion_id_fk`) REFERENCES `assertion` (`assertion_id`) ON DELETE SET NULL;

INSERT INTO
    `rule` (`role_id_fk`, `resource`, `privileges`, `permission`)
SELECT 
    t6.`role_id`,
    CONCAT('/logging/', t5.project_id) AS `resource`,
    '__default,create,edit,delete,save' AS `privileges`,
    'allow' AS `permission`
FROM 
    `task` t1,
    `task` t2, 
    `task_user` t3, 
    `project_task` t4, 
    `project` t5,
    `role` t6
WHERE 
    t1.`task_id` = t3.`task_id_fk` AND
    t2.`task_id` = t1.`task_id_fk` AND 
    t4.`task_id_fk` = t2.`task_id` AND 
    t5.`project_id` = t4.`project_id_fk` AND
    t6.`user_id_fk` = t3.`user_id_fk`
GROUP BY t3.`user_id_fk`, t5.`project_id`;   
        
CREATE TABLE IF NOT EXISTS `resource` (
  `resource_id` INT NOT NULL AUTO_INCREMENT,
  `resource_locale` VARCHAR(5) NOT NULL,
  `key` VARCHAR(255) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`resource_id`)
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ENGINE=ndbcluster;

ALTER TABLE 
    `resource` 
ADD 
    UNIQUE `resource_uidx_01` (`key`, `resource_locale`);
    
INSERT INTO `resource` (`resource_id`, `resource_locale`, `key`, `message`) VALUES
(1, 'de_DE', 'page.content.toolbar.new', 'Neu'),
(2, 'de_DE', 'page.content.tabs.company', 'Unternehmen'),
(3, 'de_DE', 'page.content.tabs.company.grid.header.row.companyId', 'ID'),
(4, 'de_DE', 'page.content.tabs.company.grid.header.row.name', 'Name'),
(5, 'de_DE', 'page.content.tabs.company.grid.header.row.email', 'E-Mail'),
(6, 'de_DE', 'page.content.tabs.company.grid.header.row.phone', 'Telefon'),
(7, 'de_DE', 'page.content.tabs.company.grid.header.row.actions', 'Aktionen'),
(8, 'de_DE', 'page.content.tabs.company.grid.footer.row.companyId', 'ID'),
(9, 'de_DE', 'page.content.tabs.company.grid.footer.row.name', 'Name'),
(10, 'de_DE', 'page.content.tabs.company.grid.footer.row.email', 'E-Mail'),
(11, 'de_DE', 'page.content.tabs.company.grid.footer.row.phone', 'Telefon'),
(12, 'de_DE', 'page.content.tabs.company.grid.footer.row.actions', 'Aktionen'),
(13, 'en_US', 'page.content.toolbar.new', 'New'),
(14, 'en_US', 'page.content.tabs.company', 'Companies'),
(15, 'en_US', 'page.content.tabs.company.grid.header.row.companyId', 'ID'),
(16, 'en_US', 'page.content.tabs.company.grid.header.row.name', 'Name'),
(17, 'en_US', 'page.content.tabs.company.grid.header.row.email', 'Mail'),
(18, 'en_US', 'page.content.tabs.company.grid.header.row.phone', 'Phone'),
(19, 'en_US', 'page.content.tabs.company.grid.header.row.actions', 'Actions'),
(20, 'en_US', 'page.content.tabs.company.grid.footer.row.companyId', 'ID'),
(21, 'en_US', 'page.content.tabs.company.grid.footer.row.name', 'Name'),
(22, 'en_US', 'page.content.tabs.company.grid.footer.row.email', 'Mail'),
(23, 'en_US', 'page.content.tabs.company.grid.footer.row.phone', 'Phone'),
(24, 'en_US', 'page.content.tabs.company.grid.footer.row.actions', 'Actions'),
(25, 'en_US', 'page.content.tabs.resource', 'tab.label.resource'),
(26, 'en_US', 'page.content.tabs.resource.grid.header.row.resourceId', 'ID'),
(27, 'en_US', 'page.content.tabs.resource.grid.header.row.key', 'Key'),
(28, 'en_US', 'page.content.tabs.resource.grid.header.row.locale', 'Locale'),
(29, 'en_US', 'page.content.tabs.resource.grid.header.row.message', 'Value'),
(30, 'en_US', 'page.content.tabs.resource.grid.header.row.actions', 'Actions'),
(31, 'en_US', 'page.content.tabs.resource.grid.footer.row.resourceId', 'ID'),
(32, 'en_US', 'page.content.tabs.resource.grid.footer.row.key', 'Key'),
(33, 'en_US', 'page.content.tabs.resource.grid.footer.row.locale', 'Locale'),
(34, 'en_US', 'page.content.tabs.resource.grid.footer.row.message', 'Value'),
(35, 'en_US', 'page.content.tabs.resource.grid.footer.row.actions', 'Actions'),
(36, 'en_US', 'page.content.tabs.resources', 'Resources'),
(37, 'en_US', 'page.content.tabs.resources.resources', 'Resources'),
(38, 'en_US', 'page.content.toolbar.back', 'Back'),
(39, 'en_US', 'page.content.toolbar.save', 'Save'),
(40, 'en_US', 'page.content.toolbar.delete', 'Delete'),
(41, 'en_US', 'title.resource.view', 'Translation'),
(42, 'en_US', 'title.resource.overview', 'Translations'),
(43, 'en_US', 'page.content.tabs.company.company', 'Base Data'),
(44, 'en_US', 'page.content.tabs.company.external', 'External'),
(45, 'en_US', 'page.content.tabs.employees', 'Employees'),
(47, 'en_US', 'page.content.tabs.employees.employeeGrid.header.row.personId', 'ID'),
(48, 'en_US', 'page.content.tabs.employees.employeeGrid.header.row.fullName', 'Name'),
(49, 'en_US', 'page.content.tabs.employees.employeeGrid.header.row.email', 'Mail'),
(50, 'en_US', 'page.content.tabs.employees.employeeGrid.header.row.phone', 'Phone'),
(51, 'en_US', 'page.content.tabs.employees.employeeGrid.header.row.actions', 'Actions'),
(53, 'en_US', 'page.content.tabs.employees.employeeGrid.footer.row.personId', 'ID'),
(54, 'en_US', 'page.content.tabs.employees.employeeGrid.footer.row.fullName', 'Name'),
(55, 'en_US', 'page.content.tabs.employees.employeeGrid.footer.row.email', 'Mail'),
(56, 'en_US', 'page.content.tabs.employees.employeeGrid.footer.row.phone', 'Phone'),
(57, 'en_US', 'page.content.tabs.employees.employeeGrid.footer.row.actions', 'Actions'),
(58, 'en_US', 'page.content.tabs.address', 'Addresses'),
(60, 'en_US', 'page.content.tabs.address.addressGrid.header.row.addressId', 'ID'),
(61, 'en_US', 'page.content.tabs.address.addressGrid.header.row.fullAddress', 'Address'),
(62, 'en_US', 'page.content.tabs.address.addressGrid.header.row.addressTypeIdFk', 'Type'),
(63, 'en_US', 'page.content.tabs.address.addressGrid.header.row.actions', 'Actions'),
(65, 'en_US', 'page.content.tabs.address.addressGrid.footer.row.addressId', 'ID'),
(66, 'en_US', 'page.content.tabs.address.addressGrid.footer.row.fullAddress', 'Address'),
(67, 'en_US', 'page.content.tabs.address.addressGrid.footer.row.addressTypeIdFk', 'Type'),
(68, 'en_US', 'page.content.tabs.address.addressGrid.footer.row.actions', 'Actions'),
(69, 'en_US', 'page.content.toolbar.createAddress', 'New Address'),
(70, 'en_US', 'page.content.tabs.note', 'Notes'),
(71, 'en_US', 'page.content.tabs.note.grid.header.row.noteId', 'ID'),
(72, 'en_US', 'page.content.tabs.note.grid.header.row.subject', 'Subject'),
(73, 'en_US', 'page.content.tabs.note.grid.header.row.noteTypeName', 'Type'),
(74, 'en_US', 'page.content.tabs.note.grid.header.row.createUserUsername', 'from'),
(75, 'en_US', 'page.content.tabs.note.grid.header.row.remindUserUsername', 'for'),
(76, 'en_US', 'page.content.tabs.note.grid.header.row.remindAt', 'due to'),
(77, 'en_US', 'page.content.tabs.note.grid.header.row.actions', 'Actions'),
(78, 'en_US', 'page.content.tabs.note.grid.footer.row.noteId', 'ID'),
(79, 'en_US', 'page.content.tabs.note.grid.footer.row.subject', 'Subject'),
(80, 'en_US', 'page.content.tabs.note.grid.footer.row.noteTypeName', 'Type'),
(81, 'en_US', 'page.content.tabs.note.grid.footer.row.createUserUsername', 'from'),
(82, 'en_US', 'page.content.tabs.note.grid.footer.row.remindUserUsername', 'for'),
(83, 'en_US', 'page.content.tabs.note.grid.footer.row.remindAt', 'due to'),
(84, 'en_US', 'page.content.tabs.note.grid.footer.row.actions', 'Actions'),
(85, 'en_US', 'page.content.tabs.note.note', 'Details'),
(86, 'en_US', 'page.content.tabs.person', 'Persons'),
(87, 'en_US', 'page.content.tabs.person.grid.header.row.personId', 'ID'),
(88, 'en_US', 'page.content.tabs.person.grid.header.row.fullName', 'Name'),
(89, 'en_US', 'page.content.tabs.person.grid.header.row.email', 'Mail'),
(90, 'en_US', 'page.content.tabs.person.grid.header.row.phone', 'Phone'),
(91, 'en_US', 'page.content.tabs.person.grid.header.row.actions', 'Actions'),
(92, 'en_US', 'page.content.tabs.person.grid.footer.row.personId', 'ID'),
(93, 'en_US', 'page.content.tabs.person.grid.footer.row.fullName', 'Name'),
(94, 'en_US', 'page.content.tabs.person.grid.footer.row.email', 'Mail'),
(95, 'en_US', 'page.content.tabs.person.grid.footer.row.phone', 'Phone'),
(96, 'en_US', 'page.content.tabs.person.grid.footer.row.actions', 'Actions'),
(97, 'en_US', 'page.content.tabs.person.person', 'Base Data'),
(98, 'en_US', 'page.content.tabs.contact-data', 'Contact Data'),
(99, 'en_US', 'page.content.tabs.contact-data.contact-dat', 'Contact Data'),
(100, 'en_US', 'page.content.tabs.account', 'Account'),
(101, 'en_US', 'page.content.tabs.account.account', 'Account'),
(102, 'en_US', 'page.content.toolbar.deleteLogging', 'Delete Logging'),
(103, 'en_US', 'page.content.toolbar.editLogging', 'Edit Logging'),
(104, 'en_US', 'page.content.tabs.logging', 'Loggings'),
(105, 'en_US', 'page.content.tabs.logging.grid.header.row.taskUserId', 'ID'),
(106, 'en_US', 'page.content.tabs.logging.grid.header.row.projectName', 'Project'),
(107, 'en_US', 'page.content.tabs.logging.grid.header.row.taskName', 'Task'),
(108, 'en_US', 'page.content.tabs.logging.grid.header.row.from', 'from'),
(109, 'en_US', 'page.content.tabs.logging.grid.header.row.until', 'until'),
(110, 'en_US', 'page.content.tabs.logging.grid.footer.row.taskUserId', 'ID'),
(111, 'en_US', 'page.content.tabs.logging.grid.footer.row.projectName', 'Project'),
(112, 'en_US', 'page.content.tabs.logging.grid.footer.row.taskName', 'Task'),
(113, 'en_US', 'page.content.tabs.logging.grid.footer.row.from', 'from'),
(114, 'en_US', 'page.content.tabs.logging.grid.footer.row.until', 'until'),
(115, 'en_US', 'page.content.tabs.logging.logged', 'My Loggings'),
(116, 'en_US', 'page.content.tabs.logging.logging', 'Logging'),
(117, 'de_DE', 'page.content.toolbar.deleteLogging', 'Zeit löschen'),
(118, 'de_DE', 'page.content.toolbar.editLogging', 'Zeit bearbeiten'),
(119, 'de_DE', 'page.content.tabs.logging', 'Zeiten'),
(120, 'de_DE', 'page.content.tabs.logging.grid.header.row.taskUserId', 'ID'),
(121, 'de_DE', 'page.content.tabs.logging.grid.header.row.projectName', 'Projekt'),
(122, 'de_DE', 'page.content.tabs.logging.grid.header.row.taskName', 'Task'),
(123, 'de_DE', 'page.content.tabs.logging.grid.header.row.from', 'von'),
(124, 'de_DE', 'page.content.tabs.logging.grid.header.row.until', 'bis'),
(125, 'de_DE', 'page.content.tabs.logging.grid.footer.row.taskUserId', 'ID'),
(126, 'de_DE', 'page.content.tabs.logging.grid.footer.row.projectName', 'Projekt'),
(127, 'de_DE', 'page.content.tabs.logging.grid.footer.row.taskName', 'Task'),
(128, 'de_DE', 'page.content.tabs.logging.grid.footer.row.from', 'von'),
(129, 'de_DE', 'page.content.tabs.logging.grid.footer.row.until', 'bis'),
(130, 'de_DE', 'page.content.tabs.resource', 'tab.label.resource'),
(131, 'de_DE', 'page.content.tabs.resource.grid.header.row.resourceId', 'ID'),
(132, 'de_DE', 'page.content.tabs.resource.grid.header.row.key', 'Key'),
(133, 'de_DE', 'page.content.tabs.resource.grid.header.row.locale', 'Locale'),
(134, 'de_DE', 'page.content.tabs.resource.grid.header.row.message', 'Value'),
(135, 'de_DE', 'page.content.tabs.resource.grid.header.row.actions', 'Actions'),
(136, 'de_DE', 'page.content.tabs.resource.grid.footer.row.resourceId', 'ID'),
(137, 'de_DE', 'page.content.tabs.resource.grid.footer.row.key', 'Key'),
(138, 'de_DE', 'page.content.tabs.resource.grid.footer.row.locale', 'Locale'),
(139, 'de_DE', 'page.content.tabs.resource.grid.footer.row.message', 'Value'),
(140, 'de_DE', 'page.content.tabs.resource.grid.footer.row.actions', 'Actions'),
(141, 'de_DE', 'page.content.tabs.resources', 'Resources'),
(142, 'de_DE', 'page.content.tabs.resources.resources', 'Resources'),
(143, 'de_DE', 'page.content.toolbar.back', 'Zurück'),
(144, 'de_DE', 'page.content.toolbar.save', 'Speichern'),
(145, 'de_DE', 'page.content.toolbar.delete', 'Löschen'),
(146, 'en_US', 'page.content.tabs.project', 'Projects'),
(147, 'en_US', 'page.content.tabs.project.grid.header.row.projectId', 'ID'),
(148, 'en_US', 'page.content.tabs.project.grid.header.row.name', 'Name'),
(149, 'en_US', 'page.content.tabs.project.grid.header.row.companyName', 'Customer'),
(150, 'en_US', 'page.content.tabs.project.grid.header.row.actions', 'Actions'),
(151, 'en_US', 'page.content.tabs.project.grid.footer.row.projectId', 'ID'),
(152, 'en_US', 'page.content.tabs.project.grid.footer.row.name', 'Name'),
(153, 'en_US', 'page.content.tabs.project.grid.footer.row.companyName', 'Customer'),
(154, 'en_US', 'page.content.tabs.project.grid.footer.row.actions', 'Actions'),
(155, 'en_US', 'page.content.project.project', 'Project'),
(156, 'en_US', 'page.content.project.project.project', 'Project'),
(157, 'en_US', 'page.content.project.user', 'User'),
(159, 'en_US', 'page.content.project.user.userGrid.header.row.userId', 'ID'),
(160, 'en_US', 'page.content.project.user.userGrid.header.row.username', 'Username'),
(161, 'en_US', 'page.content.project.user.userGrid.header.row.userRole', 'Role'),
(163, 'en_US', 'page.content.project.user.userGrid.footer.row.userId', 'ID'),
(164, 'en_US', 'page.content.project.user.userGrid.footer.row.username', 'Username'),
(165, 'en_US', 'page.content.project.user.userGrid.footer.row.userRole', 'Role'),
(166, 'en_US', 'page.content.project.logging', 'Loggings'),
(167, 'en_US', 'page.content.project.task', 'Tasks'),
(168, 'en_US', 'page.content.project.estimation', 'Estimations'),
(171, 'en_US', 'page.content.tabs.user', 'Users'),
(172, 'en_US', 'page.content.tabs.user.grid.header.row.userId', 'ID'),
(173, 'en_US', 'page.content.tabs.user.grid.header.row.roleName', 'Role'),
(174, 'en_US', 'page.content.tabs.user.grid.header.row.username', 'Username'),
(175, 'en_US', 'page.content.tabs.user.grid.header.row.email', 'E-Mail'),
(176, 'en_US', 'page.content.tabs.user.grid.header.row.actions', 'Actions'),
(177, 'en_US', 'page.content.tabs.user.grid.footer.row.userId', 'ID'),
(178, 'en_US', 'page.content.tabs.user.grid.footer.row.roleName', 'Role'),
(179, 'en_US', 'page.content.tabs.user.grid.footer.row.username', 'Username'),
(180, 'en_US', 'page.content.tabs.user.grid.footer.row.email', 'E-Mail'),
(181, 'en_US', 'page.content.tabs.user.grid.footer.row.actions', 'Actions'),
(182, 'en_US', 'page.content.tabs.user.user', 'User Data'),
(183, 'en_US', 'page.content.tabs.ldap', 'LDAP'),
(184, 'en_US', 'page.content.tabs.ldap.ldap', 'LDAP'),
(185, 'en_US', 'page.content.tabs.settings', 'Settings'),
(186, 'en_US', 'page.content.tabs.settings.settings', 'Settings'),
(187, 'en_US', 'page.content.tabs.smtp', 'SMTP'),
(188, 'en_US', 'page.content.tabs.smtp.smtp', 'SMTP'),
(189, 'en_US', 'page.content.tabs.report', 'Reports'),
(190, 'en_US', 'page.content.tabs.report.grid.header.row.reportId', 'ID'),
(191, 'en_US', 'page.content.tabs.report.grid.header.row.name', 'Name'),
(192, 'en_US', 'page.content.tabs.report.grid.header.row.actions', 'Actions'),
(193, 'en_US', 'page.content.tabs.report.grid.footer.row.reportId', 'ID'),
(194, 'en_US', 'page.content.tabs.report.grid.footer.row.name', 'Name'),
(195, 'en_US', 'page.content.tabs.report.grid.footer.row.actions', 'Actions'),
(196, 'en_US', 'page.content.tabs.reports', 'Report'),
(197, 'en_US', 'page.content.tabs.reports.reports', 'Report'),
(202, 'en_US', 'page.content.tabs.template', 'Templates'),
(203, 'en_US', 'page.content.tabs.template.grid.header.row.templateId', 'ID'),
(204, 'en_US', 'page.content.tabs.template.grid.header.row.name', 'Name'),
(205, 'en_US', 'page.content.tabs.template.grid.header.row.actions', 'Actions'),
(206, 'en_US', 'page.content.tabs.template.grid.footer.row.templateId', 'ID'),
(207, 'en_US', 'page.content.tabs.template.grid.footer.row.name', 'Name'),
(208, 'en_US', 'page.content.tabs.template.grid.footer.row.actions', 'Actions'),
(209, 'en_US', 'page.content.tabs.template.template', 'Template'),
(210, 'en_US', 'page.content.tabs.tasks', 'Tasks'),
(235, 'en_US', 'page.content.tabs.company.company.name', 'Name'),
(236, 'en_US', 'page.content.tabs.company.company.additionalName', 'Addional Name'),
(237, 'en_US', 'page.content.tabs.company.company.email', 'Mail'),
(238, 'en_US', 'page.content.tabs.company.company.phone', 'Phone'),
(239, 'en_US', 'page.content.tabs.company.company.telefax', 'Telefax'),
(240, 'en_US', 'page.content.tabs.company.company.website', 'Website'),
(241, 'en_US', 'page.content.tabs.company.company.companyIdFk', 'Related Company'),
(242, 'en_US', 'page.content.tabs.company.external.customerNumber', 'Customer Number'),
(306, 'en_US', 'title.project.view.toolbar', 'title.project.view.toolbar'),
(319, 'en_US', 'page.content.tabs.employees.employeeGrid.header.row.personIdFk', ''),
(325, 'en_US', 'page.content.tabs.employees.employeeGrid.footer.row.personIdFk', ''),
(332, 'en_US', 'page.content.tabs.address.addressGrid.header.row.addressIdFk', ''),
(337, 'en_US', 'page.content.tabs.address.addressGrid.footer.row.addressIdFk', ''),
(443, 'en_US', 'page.content.tabs.person.person.salutationIdFk', 'Salutation'),
(444, 'en_US', 'page.content.tabs.person.person.firstname', 'Firstname'),
(445, 'en_US', 'page.content.tabs.person.person.lastname', 'Lastname'),
(446, 'en_US', 'page.content.tabs.person.person.title', 'Title'),
(447, 'en_US', 'page.content.tabs.person.person.position', 'Position'),
(448, 'en_US', 'page.content.tabs.person.person.companyIdFk', 'Company'),
(449, 'en_US', 'page.content.tabs.contact-data.contact-dat.email', 'Mail'),
(450, 'en_US', 'page.content.tabs.contact-data.contact-dat.phone', 'Phone'),
(451, 'en_US', 'page.content.tabs.contact-data.contact-dat.telefax', 'Telefax'),
(452, 'en_US', 'page.content.tabs.contact-data.contact-dat.mobile', 'Mobile'),
(453, 'en_US', 'page.content.tabs.account.account.userIdFk', 'Account'),
(454, 'de_DE', 'page.content.tabs.company.company', 'Stammdaten'),
(455, 'de_DE', 'page.content.tabs.company.company.name', 'Name'),
(456, 'de_DE', 'page.content.tabs.company.company.additionalName', 'Namenszusatz'),
(457, 'de_DE', 'page.content.tabs.company.company.email', 'E-Mail'),
(458, 'de_DE', 'page.content.tabs.company.company.phone', 'Telefon'),
(459, 'de_DE', 'page.content.tabs.company.company.telefax', 'Telefax'),
(460, 'de_DE', 'page.content.tabs.company.company.website', 'Webseite'),
(461, 'de_DE', 'page.content.tabs.company.company.companyIdFk', 'Verknüpftes Unternehmen'),
(462, 'de_DE', 'page.content.tabs.company.external', 'Extern'),
(463, 'de_DE', 'page.content.tabs.company.external.customerNumber', 'Kundennummer'),
(464, 'de_DE', 'page.content.tabs.employees', 'Mitarbeiter'),
(465, 'de_DE', 'page.content.tabs.employees.employeeGrid.header.row.personIdFk', ''),
(466, 'de_DE', 'page.content.tabs.employees.employeeGrid.header.row.personId', 'ID'),
(467, 'de_DE', 'page.content.tabs.employees.employeeGrid.header.row.fullName', 'Name'),
(468, 'de_DE', 'page.content.tabs.employees.employeeGrid.header.row.email', 'E-Mail'),
(469, 'de_DE', 'page.content.tabs.employees.employeeGrid.header.row.phone', 'Telefon'),
(470, 'de_DE', 'page.content.tabs.employees.employeeGrid.header.row.actions', 'Aktionen'),
(471, 'de_DE', 'page.content.tabs.employees.employeeGrid.footer.row.personIdFk', ''),
(472, 'de_DE', 'page.content.tabs.employees.employeeGrid.footer.row.personId', 'ID'),
(473, 'de_DE', 'page.content.tabs.employees.employeeGrid.footer.row.fullName', 'Name'),
(474, 'de_DE', 'page.content.tabs.employees.employeeGrid.footer.row.email', 'E-Mail'),
(475, 'de_DE', 'page.content.tabs.employees.employeeGrid.footer.row.phone', 'Telefon'),
(476, 'de_DE', 'page.content.tabs.employees.employeeGrid.footer.row.actions', 'Aktionen'),
(477, 'de_DE', 'page.content.tabs.address', 'Adressen'),
(478, 'de_DE', 'page.content.tabs.address.addressGrid.header.row.addressIdFk', ''),
(479, 'de_DE', 'page.content.tabs.address.addressGrid.header.row.addressId', 'ID'),
(480, 'de_DE', 'page.content.tabs.address.addressGrid.header.row.fullAddress', 'Adresse'),
(481, 'de_DE', 'page.content.tabs.address.addressGrid.header.row.addressTypeIdFk', 'Typ'),
(482, 'de_DE', 'page.content.tabs.address.addressGrid.header.row.actions', 'Aktionen'),
(483, 'de_DE', 'page.content.tabs.address.addressGrid.footer.row.addressIdFk', ''),
(484, 'de_DE', 'page.content.tabs.address.addressGrid.footer.row.addressId', 'ID'),
(485, 'de_DE', 'page.content.tabs.address.addressGrid.footer.row.fullAddress', 'Adresse'),
(486, 'de_DE', 'page.content.tabs.address.addressGrid.footer.row.addressTypeIdFk', 'Typ'),
(487, 'de_DE', 'page.content.tabs.address.addressGrid.footer.row.actions', 'Aktionen'),
(488, 'de_DE', 'page.content.toolbar.createAddress', 'Neue Adresse'),
(489, 'de_DE', 'page.content.tabs.note', 'Wiedervorlagen'),
(490, 'de_DE', 'page.content.tabs.note.grid.header.row.noteId', 'ID'),
(491, 'de_DE', 'page.content.tabs.note.grid.header.row.subject', 'Betreff'),
(492, 'de_DE', 'page.content.tabs.note.grid.header.row.noteTypeName', 'Typ'),
(493, 'de_DE', 'page.content.tabs.note.grid.header.row.createUserUsername', 'von'),
(494, 'de_DE', 'page.content.tabs.note.grid.header.row.remindUserUsername', 'für'),
(495, 'de_DE', 'page.content.tabs.note.grid.header.row.remindAt', 'fällig'),
(496, 'de_DE', 'page.content.tabs.note.grid.header.row.actions', 'Aktionen'),
(497, 'de_DE', 'page.content.tabs.note.grid.footer.row.noteId', 'ID'),
(498, 'de_DE', 'page.content.tabs.note.grid.footer.row.subject', 'Betreff'),
(499, 'de_DE', 'page.content.tabs.note.grid.footer.row.noteTypeName', 'Typ'),
(500, 'de_DE', 'page.content.tabs.note.grid.footer.row.createUserUsername', 'von'),
(501, 'de_DE', 'page.content.tabs.note.grid.footer.row.remindUserUsername', 'für'),
(502, 'de_DE', 'page.content.tabs.note.grid.footer.row.remindAt', 'fällig'),
(503, 'de_DE', 'page.content.tabs.note.grid.footer.row.actions', 'Aktionen'),
(504, 'de_DE', 'page.content.tabs.note.note', 'Details'),
(505, 'de_DE', 'page.content.tabs.note.note.subject', 'Betreff'),
(506, 'de_DE', 'page.content.tabs.note.note.remindAt', 'Erinnern am'),
(507, 'de_DE', 'page.content.tabs.note.note.note', 'Nachricht'),
(508, 'de_DE', 'page.content.tabs.note.note.remindUserIdFk', 'Benutzer'),
(509, 'de_DE', 'page.content.tabs.note.note.noteTypeIdFk', 'Typ'),
(510, 'de_DE', 'page.content.tabs.personen', 'Personen'),
(511, 'de_DE', 'page.content.tabs.personen.personGrid.header.row.personIdFk', ''),
(512, 'de_DE', 'page.content.tabs.personen.personGrid.header.row.personId', 'ID'),
(513, 'de_DE', 'page.content.tabs.personen.personGrid.header.row.fullName', 'Name'),
(514, 'de_DE', 'page.content.tabs.personen.personGrid.footer.row.personIdFk', ''),
(515, 'de_DE', 'page.content.tabs.personen.personGrid.footer.row.personId', 'ID'),
(516, 'de_DE', 'page.content.tabs.personen.personGrid.footer.row.fullName', 'Name'),
(517, 'de_DE', 'page.content.tabs.companies', 'Unternehmen'),
(518, 'de_DE', 'page.content.tabs.companies.companyGrid.header.row.companyIdFk', ''),
(519, 'de_DE', 'page.content.tabs.companies.companyGrid.header.row.companyId', 'ID'),
(520, 'de_DE', 'page.content.tabs.companies.companyGrid.header.row.name', 'Name'),
(521, 'de_DE', 'page.content.tabs.companies.companyGrid.footer.row.companyIdFk', ''),
(522, 'de_DE', 'page.content.tabs.companies.companyGrid.footer.row.companyId', 'ID'),
(523, 'de_DE', 'page.content.tabs.companies.companyGrid.footer.row.name', 'Name'),
(524, 'en_US', 'page.content.tabs.note.note.subject', 'Subject'),
(525, 'en_US', 'page.content.tabs.note.note.remindAt', 'Remind at'),
(526, 'en_US', 'page.content.tabs.note.note.note', 'Note'),
(527, 'en_US', 'page.content.tabs.note.note.remindUserIdFk', 'User'),
(528, 'en_US', 'page.content.tabs.note.note.noteTypeIdFk', 'Type'),
(529, 'en_US', 'page.content.tabs.personen', 'Persons'),
(530, 'en_US', 'page.content.tabs.personen.personGrid.header.row.personIdFk', ''),
(531, 'en_US', 'page.content.tabs.personen.personGrid.header.row.personId', 'ID'),
(532, 'en_US', 'page.content.tabs.personen.personGrid.header.row.fullName', 'Name'),
(533, 'en_US', 'page.content.tabs.personen.personGrid.footer.row.personIdFk', ''),
(534, 'en_US', 'page.content.tabs.personen.personGrid.footer.row.personId', 'ID'),
(535, 'en_US', 'page.content.tabs.personen.personGrid.footer.row.fullName', 'Name'),
(536, 'en_US', 'page.content.tabs.companies', 'Companies'),
(537, 'en_US', 'page.content.tabs.companies.companyGrid.header.row.companyIdFk', ''),
(538, 'en_US', 'page.content.tabs.companies.companyGrid.header.row.companyId', 'ID'),
(539, 'en_US', 'page.content.tabs.companies.companyGrid.header.row.name', 'Name'),
(540, 'en_US', 'page.content.tabs.companies.companyGrid.footer.row.companyIdFk', ''),
(541, 'en_US', 'page.content.tabs.companies.companyGrid.footer.row.companyId', 'ID'),
(542, 'en_US', 'page.content.tabs.companies.companyGrid.footer.row.name', 'Name'),
(543, 'de_DE', 'page.content.tabs.person', 'Personen'),
(544, 'de_DE', 'page.content.tabs.person.grid.header.row.personId', 'ID'),
(545, 'de_DE', 'page.content.tabs.person.grid.header.row.fullName', 'Name'),
(546, 'de_DE', 'page.content.tabs.person.grid.header.row.email', 'E-Mail'),
(547, 'de_DE', 'page.content.tabs.person.grid.header.row.phone', 'Telefon'),
(548, 'de_DE', 'page.content.tabs.person.grid.header.row.actions', 'Aktionen'),
(549, 'de_DE', 'page.content.tabs.person.grid.footer.row.personId', 'ID'),
(550, 'de_DE', 'page.content.tabs.person.grid.footer.row.fullName', 'Name'),
(551, 'de_DE', 'page.content.tabs.person.grid.footer.row.email', 'E-Mail'),
(552, 'de_DE', 'page.content.tabs.person.grid.footer.row.phone', 'Telefon'),
(553, 'de_DE', 'page.content.tabs.person.grid.footer.row.actions', 'Aktionen'),
(554, 'de_DE', 'page.content.tabs.person.person', 'Stammdaten'),
(555, 'de_DE', 'page.content.tabs.person.person.salutationIdFk', 'Anrede'),
(556, 'de_DE', 'page.content.tabs.person.person.firstname', 'Vorname'),
(557, 'de_DE', 'page.content.tabs.person.person.lastname', 'Nachname'),
(558, 'de_DE', 'page.content.tabs.person.person.title', 'Titel'),
(559, 'de_DE', 'page.content.tabs.person.person.position', 'Position'),
(560, 'de_DE', 'page.content.tabs.person.person.companyIdFk', 'Unternehmen'),
(561, 'de_DE', 'page.content.tabs.contact-data', 'Kontaktdaten'),
(562, 'de_DE', 'page.content.tabs.contact-data.contact-dat', 'Kontaktdaten'),
(563, 'de_DE', 'page.content.tabs.contact-data.contact-dat.email', 'E-Mail'),
(564, 'de_DE', 'page.content.tabs.contact-data.contact-dat.phone', 'Telefon'),
(565, 'de_DE', 'page.content.tabs.contact-data.contact-dat.telefax', 'Telefax'),
(566, 'de_DE', 'page.content.tabs.contact-data.contact-dat.mobile', 'Mobilfunknummer'),
(567, 'de_DE', 'page.content.tabs.account', 'Benutzerkonto'),
(568, 'de_DE', 'page.content.tabs.account.account', 'Benutzerkonto'),
(569, 'de_DE', 'page.content.tabs.account.account.userIdFk', 'Benutzerkonto'),
(570, 'de_DE', 'page.content.tabs.logging.logged', 'Meine Zeiten'),
(571, 'de_DE', 'page.content.tabs.logging.logging', 'Zeiten'),
(572, 'de_DE', 'page.content.tabs.logging.logging.projectIdFk', 'Projekt'),
(573, 'de_DE', 'page.content.tabs.logging.logging.from', 'von'),
(574, 'de_DE', 'page.content.tabs.logging.logging.until', 'bis'),
(575, 'de_DE', 'page.content.tabs.logging.logging.description', 'Beschreibung'),
(576, 'en_US', 'page.content.tabs.logging.logging.projectIdFk', 'Project'),
(577, 'en_US', 'page.content.tabs.logging.logging.from', 'from'),
(578, 'en_US', 'page.content.tabs.logging.logging.until', 'until'),
(579, 'en_US', 'page.content.tabs.logging.logging.description', 'Description'),
(580, 'de_DE', 'page.content.tabs.project', 'Projekte'),
(581, 'de_DE', 'page.content.tabs.project.grid.header.row.projectId', 'ID'),
(582, 'de_DE', 'page.content.tabs.project.grid.header.row.name', 'Name'),
(583, 'de_DE', 'page.content.tabs.project.grid.header.row.companyName', 'Kunde'),
(584, 'de_DE', 'page.content.tabs.project.grid.header.row.actions', 'Aktionen'),
(585, 'de_DE', 'page.content.tabs.project.grid.footer.row.projectId', 'ID'),
(586, 'de_DE', 'page.content.tabs.project.grid.footer.row.name', 'Name'),
(587, 'de_DE', 'page.content.tabs.project.grid.footer.row.companyName', 'Kunde'),
(588, 'de_DE', 'page.content.tabs.project.grid.footer.row.actions', 'Aktionen'),
(589, 'en_US', 'page.content.project.project.project.name', 'Name'),
(590, 'en_US', 'page.content.project.project.project.projectIdFk', 'Parent Project'),
(591, 'en_US', 'page.content.project.project.project.companyIdFk', 'Customer'),
(592, 'en_US', 'page.content.project.user.userGrid.header.row.userIdFk', ''),
(593, 'en_US', 'page.content.project.user.userGrid.footer.row.userIdFk', ''),
(594, 'de_DE', 'page.content.project.project', 'Projekt'),
(595, 'de_DE', 'page.content.project.project.project', 'Projekt'),
(596, 'de_DE', 'page.content.project.project.project.name', 'Name'),
(597, 'de_DE', 'page.content.project.project.project.projectIdFk', 'Übergeordnetes Projekt'),
(598, 'de_DE', 'page.content.project.project.project.companyIdFk', 'Kunde'),
(599, 'de_DE', 'page.content.project.user', 'Benutzer'),
(600, 'de_DE', 'page.content.project.user.userGrid.header.row.userIdFk', ''),
(601, 'de_DE', 'page.content.project.user.userGrid.header.row.userId', 'ID'),
(602, 'de_DE', 'page.content.project.user.userGrid.header.row.username', 'Benutzername'),
(603, 'de_DE', 'page.content.project.user.userGrid.header.row.userRole', 'Rolle'),
(604, 'de_DE', 'page.content.project.user.userGrid.footer.row.userIdFk', ''),
(605, 'de_DE', 'page.content.project.user.userGrid.footer.row.userId', 'ID'),
(606, 'de_DE', 'page.content.project.user.userGrid.footer.row.username', 'Benutzername'),
(607, 'de_DE', 'page.content.project.user.userGrid.footer.row.userRole', 'Rolle'),
(608, 'de_DE', 'page.content.project.logging', 'Zeiten'),
(609, 'de_DE', 'page.content.project.task', 'Tasks'),
(610, 'de_DE', 'page.content.project.estimation', 'Schätzungen'),
(611, 'de_DE', 'content.task', 'Task Bearbeiten'),
(612, 'de_DE', 'content.task.description', 'Beschreibung'),
(613, 'de_DE', 'content.task.billable', 'Abrechenbar'),
(614, 'de_DE', 'content.task.taskTypeIdFk', 'Typ'),
(615, 'de_DE', 'content.toolbar.saveTask', 'Task Speichern'),
(616, 'en_US', 'content.task', 'Edit Task'),
(617, 'en_US', 'content.task.description', 'Description'),
(618, 'en_US', 'content.task.billable', 'Billable'),
(619, 'en_US', 'content.task.taskTypeIdFk', 'Type'),
(620, 'en_US', 'content.toolbar.saveTask', 'Save Task'),
(621, 'en_US', 'content.estimations-made', 'Estimations Made'),
(622, 'en_US', 'content.make-estimation', 'Make an Estimation'),
(623, 'en_US', 'content.make-estimation.description', 'Description'),
(624, 'en_US', 'content.make-estimation.unit', 'Unit'),
(625, 'en_US', 'content.make-estimation.complexity', 'Complexity'),
(626, 'en_US', 'content.make-estimation.quantity', 'Quantity'),
(627, 'en_US', 'content.toolbar.saveEstimation', 'Save Estimation'),
(628, 'de_DE', 'content.estimations-made', 'Abgegebene Schätzungen'),
(629, 'de_DE', 'content.make-estimation', 'Schätzung abgeben'),
(630, 'de_DE', 'content.make-estimation.description', 'Beschreibung'),
(631, 'de_DE', 'content.make-estimation.unit', 'Einheit'),
(632, 'de_DE', 'content.make-estimation.complexity', 'Komplexität'),
(633, 'de_DE', 'content.make-estimation.quantity', 'Anzahl'),
(634, 'de_DE', 'content.toolbar.saveEstimation', 'Schätzung Speichern'),
(635, 'de_DE', 'page.content.tabs.template', 'Templates'),
(636, 'de_DE', 'page.content.tabs.template.grid.header.row.templateId', 'ID'),
(637, 'de_DE', 'page.content.tabs.template.grid.header.row.name', 'Name'),
(638, 'de_DE', 'page.content.tabs.template.grid.header.row.actions', 'Aktionen'),
(639, 'de_DE', 'page.content.tabs.template.grid.footer.row.templateId', 'ID'),
(640, 'de_DE', 'page.content.tabs.template.grid.footer.row.name', 'Name'),
(641, 'de_DE', 'page.content.tabs.template.grid.footer.row.actions', 'Aktionen'),
(642, 'en_US', 'page.content.tabs.template.template.name', 'Name'),
(643, 'en_US', 'page.content.tabs.template.template.description', 'Description'),
(644, 'de_DE', 'page.content.tabs.template.template', 'Templatedaten'),
(645, 'de_DE', 'page.content.tabs.template.template.name', 'Name'),
(646, 'de_DE', 'page.content.tabs.template.template.description', 'Beschreibung'),
(647, 'de_DE', 'page.content.tabs.tasks', 'Tasks'),
(648, 'de_DE', 'page.content.tabs.report', 'Berichte'),
(649, 'de_DE', 'page.content.tabs.report.grid.header.row.reportId', 'ID'),
(650, 'de_DE', 'page.content.tabs.report.grid.header.row.name', 'Name'),
(651, 'de_DE', 'page.content.tabs.report.grid.header.row.actions', 'Aktionen'),
(652, 'de_DE', 'page.content.tabs.report.grid.footer.row.reportId', 'ID'),
(653, 'de_DE', 'page.content.tabs.report.grid.footer.row.name', 'Name'),
(654, 'de_DE', 'page.content.tabs.report.grid.footer.row.actions', 'Aktionen'),
(655, 'de_DE', 'page.content.tabs.reports', 'Bericht'),
(656, 'de_DE', 'page.content.tabs.reports.reports', 'Bericht'),
(657, 'de_DE', 'page.content.tabs.reports.reports.name', 'Name'),
(658, 'de_DE', 'page.content.tabs.reports.reports.unit', 'Unit'),
(659, 'de_DE', 'page.content.tabs.reports.reports.description', 'Beschreibung'),
(660, 'en_US', 'page.content.tabs.reports.reports.name', 'Name'),
(661, 'en_US', 'page.content.tabs.reports.reports.unit', 'Unit'),
(662, 'en_US', 'page.content.tabs.reports.reports.description', 'Description'),
(663, 'de_DE', 'page.content.tabs.resources.resources.key', 'Key'),
(664, 'de_DE', 'page.content.tabs.resources.resources.locale', 'Locale'),
(665, 'de_DE', 'page.content.tabs.resources.resources.message', 'Message'),
(666, 'en_US', 'page.content.tabs.resources.resources.key', 'Key'),
(667, 'en_US', 'page.content.tabs.resources.resources.locale', 'Locale'),
(668, 'en_US', 'page.content.tabs.resources.resources.message', 'Message'),
(669, 'en_US', 'page.content.tabs.settings.settings.emailSupport', 'Mail Support'),
(670, 'en_US', 'page.content.tabs.ldap.ldap.useLdap', 'Use'),
(671, 'en_US', 'page.content.tabs.ldap.ldap.ldapHost', 'Host'),
(672, 'en_US', 'page.content.tabs.ldap.ldap.ldapBindRequired', 'Bind required'),
(673, 'en_US', 'page.content.tabs.ldap.ldap.ldapDomain', 'Domain'),
(674, 'en_US', 'page.content.tabs.ldap.ldap.ldapDn', 'Dn'),
(675, 'en_US', 'page.content.tabs.smtp.smtp.useSmtp', 'Use'),
(676, 'en_US', 'page.content.tabs.smtp.smtp.smtpHost', 'Host'),
(677, 'en_US', 'page.content.tabs.smtp.smtp.smtpPort', 'Port'),
(678, 'en_US', 'page.content.tabs.smtp.smtp.smtpUser', 'User'),
(679, 'en_US', 'page.content.tabs.smtp.smtp.smtpPassword', 'Password'),
(680, 'de_DE', 'page.content.tabs.settings', 'Einstellungen'),
(681, 'de_DE', 'page.content.tabs.settings.settings', 'Einstellungen'),
(682, 'de_DE', 'page.content.tabs.settings.settings.emailSupport', 'E-Mail Support'),
(683, 'de_DE', 'page.content.tabs.ldap', 'LDAP'),
(684, 'de_DE', 'page.content.tabs.ldap.ldap', 'LDAP'),
(685, 'de_DE', 'page.content.tabs.ldap.ldap.useLdap', 'Verwenden'),
(686, 'de_DE', 'page.content.tabs.ldap.ldap.ldapHost', 'Host'),
(687, 'de_DE', 'page.content.tabs.ldap.ldap.ldapBindRequired', 'Bind erforderlich'),
(688, 'de_DE', 'page.content.tabs.ldap.ldap.ldapDomain', 'Domain'),
(689, 'de_DE', 'page.content.tabs.ldap.ldap.ldapDn', 'Dn'),
(690, 'de_DE', 'page.content.tabs.smtp', 'SMTP'),
(691, 'de_DE', 'page.content.tabs.smtp.smtp', 'SMTP'),
(692, 'de_DE', 'page.content.tabs.smtp.smtp.useSmtp', 'Verwenden'),
(693, 'de_DE', 'page.content.tabs.smtp.smtp.smtpHost', 'Host'),
(694, 'de_DE', 'page.content.tabs.smtp.smtp.smtpPort', 'Port'),
(695, 'de_DE', 'page.content.tabs.smtp.smtp.smtpUser', 'Benutzer'),
(696, 'de_DE', 'page.content.tabs.smtp.smtp.smtpPassword', 'Passwort'),
(697, 'de_DE', 'page.content.tabs.user', 'Benutzer'),
(698, 'de_DE', 'page.content.tabs.user.grid.header.row.userId', 'ID'),
(699, 'de_DE', 'page.content.tabs.user.grid.header.row.roleName', 'Role'),
(700, 'de_DE', 'page.content.tabs.user.grid.header.row.username', 'Username'),
(701, 'de_DE', 'page.content.tabs.user.grid.header.row.email', 'E-Mail'),
(702, 'de_DE', 'page.content.tabs.user.grid.header.row.actions', 'Actions'),
(703, 'de_DE', 'page.content.tabs.user.grid.footer.row.userId', 'ID'),
(704, 'de_DE', 'page.content.tabs.user.grid.footer.row.roleName', 'Role'),
(705, 'de_DE', 'page.content.tabs.user.grid.footer.row.username', 'Username'),
(706, 'de_DE', 'page.content.tabs.user.grid.footer.row.email', 'E-Mail'),
(707, 'de_DE', 'page.content.tabs.user.grid.footer.row.actions', 'Actions'),
(708, 'de_DE', 'page.content.tabs.user.user', 'Stammdaten'),
(709, 'de_DE', 'page.content.tabs.user.user.username', 'Benutzername'),
(710, 'de_DE', 'page.content.tabs.user.user.email', 'E-Mail'),
(711, 'de_DE', 'page.content.tabs.user.user.rate', 'Interner Verrechnungspreis'),
(712, 'de_DE', 'page.content.tabs.user.user.enabled', 'Aktiv'),
(713, 'de_DE', 'page.content.tabs.user.user.roleIdFk', 'Rolle'),
(714, 'de_DE', 'page.content.tabs.ldap.ldap.ldapSynced', 'Synchronisiert'),
(715, 'de_DE', 'page.content.tabs.ldap.ldap.syncedAt', 'Zuletzt synchronisiert am'),
(716, 'en_US', 'page.content.tabs.user.user.username', 'Username'),
(717, 'en_US', 'page.content.tabs.user.user.email', 'Mail'),
(718, 'en_US', 'page.content.tabs.user.user.rate', 'Internal Price'),
(719, 'en_US', 'page.content.tabs.user.user.enabled', 'Activ'),
(720, 'en_US', 'page.content.tabs.user.user.roleIdFk', 'Role'),
(721, 'en_US', 'page.content.tabs.ldap.ldap.ldapSynced', 'Synchronized'),
(722, 'en_US', 'page.content.tabs.ldap.ldap.syncedAt', 'Last Synchronization');

INSERT INTO `resource` (`resource_id`, `resource_locale`, `key`, `message`) VALUES
(731, 'en_US', 'page.navigation.root.note', 'ERP'),
(741, 'en_US', 'page.navigation.root.note.company', 'Companies'),
(743, 'en_US', 'page.navigation.root.note.note', 'Notes'),
(742, 'en_US', 'page.navigation.root.note.person', 'Persons'),
(730, 'en_US', 'page.navigation.root.dashboard', 'Dashboard'),
(734, 'en_US', 'page.navigation.root.logging', 'Projects'),
(747, 'en_US', 'page.navigation.root.logging.logging', 'Logging'),
(748, 'en_US', 'page.navigation.root.logging.project', 'Projects'),
(749, 'en_US', 'page.navigation.root.logging.template', 'Templates'),
(737, 'en_US', 'page.navigation.root.report', 'Reports'),
(740, 'en_US', 'page.navigation.root.setting', 'Settings'),
(746, 'en_US', 'page.navigation.root.setting.resource', 'Translations'),
(744, 'en_US', 'page.navigation.root.setting.setting', 'Settings'),
(745, 'en_US', 'page.navigation.root.setting.user', 'Users');

INSERT INTO `resource` (`resource_id`, `resource_locale`, `key`, `message`) VALUES
(750, 'de_DE', 'page.navigation.root.note', 'ERP'),
(751, 'de_DE', 'page.navigation.root.note.company', 'Unternehmen'),
(752, 'de_DE', 'page.navigation.root.note.note', 'Wiedervorlage'),
(753, 'de_DE', 'page.navigation.root.note.person', 'Personen'),
(754, 'de_DE', 'page.navigation.root.dashboard', 'Dashboard'),
(755, 'de_DE', 'page.navigation.root.logging', 'Projekte'),
(756, 'de_DE', 'page.navigation.root.logging.logging', 'Zeiten'),
(757, 'de_DE', 'page.navigation.root.logging.project', 'Projekte'),
(758, 'de_DE', 'page.navigation.root.logging.template', 'Templates'),
(759, 'de_DE', 'page.navigation.root.report', 'Berichte'),
(760, 'de_DE', 'page.navigation.root.setting', 'System'),
(761, 'de_DE', 'page.navigation.root.setting.resource', 'Übersetzungen'),
(762, 'de_DE', 'page.navigation.root.setting.setting', 'Einstellungen'),
(763, 'de_DE', 'page.navigation.root.setting.user', 'Benutzer');

INSERT INTO `resource` (`resource_id`, `resource_locale`, `key`, `message`) VALUES
(764, 'en_US', 'page.content.tabs.user.user.contractedHours', 'Contracted Hours'),
(765, 'de_DE', 'page.content.tabs.user.user.contractedHours', 'Monatliche Arbeitszeit');