<?php
/**
 * TDProject_Core
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
?>
<?php

    $request = $this->getRequest();
    // load the errors
    $errors = $request->getAttribute(TechDivision_Controller_Action_Errors::ACTION_ERRORS);
    // load the system user
    $systemUser = $request->getSession()->getAttribute(TDProject_Core_Controller_Util_WebSessionKeys::SYSTEM_USER);
	// add a 500 header to signal an internal server error
	header('HTTP/1.1 500 Internal Server Error', true, 500);

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

	<?php // $this->_getChildHtml('head'); ?>

	<body class="ui-widget ui-widget-content">
		<div id="header" class="container_12">
			<!-- START: Logo -->  
			<div id="logo" class="grid_2">
				<p>
					<a href="index.php?path=dashboard">
						<img src="www/design/core/templates/global/images/logo.png"/>
					</a>
				</p>
			</div>
			<!-- END: Logo -->
			
			<!-- START: Menu -->
			<div class="grid_10 align-right">
				<h2>Internal Server Error</h2>
			</div>
			<!-- END: Menu -->
			<div class="clear"></div>  
		</div>
		
		<div id="content" class="container_12">  
			<div class="grid_12"><?php if ($errors instanceof TechDivision_Controller_Action_Errors) { ?>
				<ul><?php foreach($errors as $error) { ?>
	                <li><?php echo nl2br($error->getMessage()); ?></li><?php } ?>
	            </ul><?php } ?>
				<p>An internal server error has occured, please contact 
				   the system administrator &lt;tw@techdivision.com&gt;!</p>
			</div>
			<div class="clear"></div>  
		</div>
		
		<div id="footer" class="container_12">  
			<div class="grid_12">
				<p>Copyright &copy; 2010 TechDivision</p>
				<div id="loader"></div>
			</div>
			<div class="clear"></div>  
		</div> 
	
	</body>

</html>