<?php

/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
?>
<div
	id="<?php echo $this->getBlockName() ?>"
	class="<?php echo $this->getCssClass() ?>"
	style="width:<?php echo $this->getWidth() ?>px">
</div>
<script type="text/javascript">
$.jqplot('<?php echo $this->getBlockName() ?>', <?php echo $this->getValue() ?>, {
    title:'<?php echo $this->getBlockTitle() ?>',
    axes:{
       xaxis:{
    	pad: 0,
        renderer:$.jqplot.DateAxisRenderer,
        tickOptions:{
          formatString:'%b&nbsp;%#d'
        }
      }
    },
    highlighter: {
      show: true,
      sizeAdjust: 7.5
    },
    cursor: {
      show: false
    }
});
</script>