<label for="<?php echo $this->getBlockName() ?>" class="<?php echo $this->getCssClass() ?>">
	<span class="title"><?php echo $this->getBlockTitle() ?>:</span><?php if ($this->isMandatory()) { ?>&nbsp;<span class="required">*</span><?php } ?>
</label>
<textarea
	style="width: <?php echo $this->getWidth() ?>px"
	id="<?php echo $this->getBlockName() ?>"
	name="<?php echo $this->getBlockName() ?>" 
	<?php if ($this->isDisabled()) { ?> disabled="disabled"<?php } ?>><?php echo $this->getValue() ?></textarea>
