<?php 
/**
 * TDProject_Core
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
?>

<?php foreach ($this->getWidgets() as $widget): ?>
	<div id="widget[<?php echo $widget->getBlockName(); ?>]" class="grid_6">
    	<?php echo $widget->toHtml(); ?>
    </div>	 
<?php endforeach;?> 