<?php

/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
?>
<script type="text/javascript" charset="utf-8">

$(document).ready(function() {
	// render tabs
	$("#tabs").tabs();
});

</script>

<div id="tabs">
	<ul><?php foreach ($this->getTabs() as $tab) { ?>
		<li><a href="#<?php echo $tab->getCssId() ?>" onclick="$('#toolbar-view').show();"><?php echo $tab->getBlockTitle() ?></a></li>
	<?php } ?></ul>
	<?php foreach ($this->getTabs() as $tab) { ?>
		<?php $this->_getChildHtml($tab->getBlockName()); ?>
	<?php } ?>
</div>